### ISSUE TITLE
Open "Projects" Link in a New Tab

### ISSUE THREAD

**Issue by thakurdiwakar** [Manishak798/Dive-to-Dev_Hacktoberfest23#12]
**Issue Description:**

I've noticed that when clicking on the "Projects Link" link in the website card section, it currently opens in the same tab. To improve user experience and navigation, I suggest modifying this behavior to make the "Projects" link open in a new tab.

**Comment by thakurdiwakar** [comment]
Hey @Manishak798 ,I would like to work on this issue Can you please assign this to me?

**Comment by Manishak798** [comment]
Sure, @thakurdiwakar, go ahead with your work.
