### ISSUE TITLE
This Repo has been Excluded from Hacktoberfest 2023

### ISSUE THREAD

**Issue by famanakis** [Manishak798/Dive-to-Dev_Hacktoberfest23#22]
Unfortunately this repo has been excluded from Hacktoberfest 2023. Pull/merge requests for this repo are not currently counting towards Hacktoberfest 2023 contributions. Maybe there is a way to contact the organizers and have this repo become included again?
![Screenshot (211)](https://github.com/Manishak798/Dive-to-Dev_Hacktoberfest23/assets/73799603/8ebab19d-cd36-4e3d-b279-3bed04504cee)

**Comment by Manishak798** [comment]
I will keep you posted about the same.
