### ISSUE TITLE
Card UI 

### ISSUE THREAD

**Issue by Dhruvrode** [Manishak798/Dive-to-Dev_Hacktoberfest23#24]
The card/ project can  be improved by adding hover effect on card.

Solution:
When we Hover on card the border colour should change and little bit zoom of card it will look good.

**Comment by Dhruvrode** [comment]
Hey  @Manishak798   i can improve the Ui please assign it to me for hacktoberfest 2023.
I would love to contribute!

**Comment by Manishak798** [comment]
Go ahead with your work, @Dhruvrode

**Comment by Dhruvrode** [comment]
Thank you so much I'll let you know when I am done

**Comment by Dhruvrode** [comment]
Hi @Manishak798   I have made the necessary PR for this issue. Make sure to label the PR with hacktoberfest-accepted after reviewing it.
#25  And please inform me if I have made a mistake .

**Comment by Dhruvrode** [comment]
Hey @Manishak798  why it saying excluded repo ??/

**Comment by Manishak798** [comment]
Unfortunately, This project has been excluded from hacktoberfest.
