### ISSUE TITLE
Align the buttom row for the site on desktop view

### ISSUE THREAD

**Issue by ariyoaresa** [Manishak798/Dive-to-Dev_Hacktoberfest23#26]
**Describe the bug**
The website is okay on mobile view, but whenever I'm on desktop view, the bottom row is not straight 

**To Reproduce**
1. Go to the website 
2. Use a desktop or change to desktop view 
3. Scroll down to the last row

**Expected behavior**
The last row wouldn't be aligned 

![Screenshot_20231007-174807](https://github.com/Manishak798/Dive-to-Dev_Hacktoberfest23/assets/108690633/22224c59-f5b5-48c2-ae67-aab4084443ee)

**Comment by Manishak798** [comment]
You can start your work now.
