### ISSUE TITLE
Have to improve the responsiveness of the site

### ISSUE THREAD

**Issue by Akangkha** [Manishak798/Dive-to-Dev_Hacktoberfest23#27]
At the breakpoint of 1006pxX672px the site layout is not structured well.
* *To Reproduce**
1. Go to 'Inspect'
2. Check the responsiveness
![Screenshot](https://github.com/Manishak798/Dive-to-Dev_Hacktoberfest23/assets/113259853/c057a9cf-327a-4c93-bb3e-bf6915f38a03)

**Desktop:**
 - Windows 11th Gen .
 - Browser [chrome]
 -  Version 117.0.5938.149 

**Additional context**
Would like to improve the design of the site if permitted.

**Comment by Manishak798** [comment]
You can start your work now.
