### ISSUE TITLE
calander

### ISSUE THREAD

**Issue by Anju-Narnolia** [Manishak798/Dive-to-Dev_Hacktoberfest23#47]
@Manishak798 I would like to add a calendar.
So can you please assign me this issue under Hacktoberfest2023?

**Comment by TanushreeBorase** [comment]
I can add calender in python ,Can you pls assign me this issue @Anju-Narnolia

**Comment by Manishak798** [comment]
Where do you want to add the calendar?

**Comment by TanushreeBorase** [comment]
as a part of contribution in the form of code for Hacktoberfest2023

**Comment by Anju-Narnolia** [comment]
> Where do you want to add the calendar?

@Manishak798 as a project just like the Amazon landing page.
about project and project link.

**Comment by Manishak798** [comment]
> > Where do you want to add the calendar?
> 
> @Manishak798 as a project just like the Amazon landing page. about project and project link.

go ahead.
