### ISSUE TITLE
Image of youtube clone and google search engine clone is not reflecting.

### ISSUE THREAD

**Issue by singhaman09** [Manishak798/Dive-to-Dev_Hacktoberfest23#52]
![image](https://github.com/Manishak798/Dive-to-Dev_Hacktoberfest23/assets/112258507/2d81ec3f-563f-4f80-904e-2a8c256906ef)
![image](https://github.com/Manishak798/Dive-to-Dev_Hacktoberfest23/assets/112258507/2e953f30-d17b-4cb1-9638-01fda08052f2)
please assign me this issue and label it with hacktoberfest .
I will raise up my PR asap.

**Comment by Manishak798** [comment]
You can start your work now.
