### ISSUE TITLE
Add a Icon for Dive to dev.

### ISSUE THREAD

**Issue by singhaman09** [Manishak798/Dive-to-Dev_Hacktoberfest23#53]
there must be icon in the navbar which makes it more impressive.

like this:
![image](https://github.com/Manishak798/Dive-to-Dev_Hacktoberfest23/assets/112258507/66c246b0-6a15-41c0-8c69-11cedc34f906)

please assign me this issue and label it with hacktoberfest.
I will raise up my PR asap.

**Comment by Manishak798** [comment]
You can work on this issue.
