### ISSUE TITLE
bug: twitter logo not updated to X

### ISSUE THREAD

**Issue by baekusboo** [Manishak798/Dive-to-Dev_Hacktoberfest23#67]
**Describe the bug**
Twitter icon is not updated in the footer.

**To Reproduce**
1. Go to the website
2. Scroll down to the footer
4. See the icon of twitter

**Expected behavior**
The latest logo of twitter (X) should be displayed instead of the bird logo.

**Screenshots**
<img width="221" alt="image" src="https://github.com/Manishak798/Dive-to-Dev_Hacktoberfest23/assets/83155556/50c4b1cd-a196-428d-b30a-75894ad9b8f5">

**Additional context**
I would like to resolve this issue for hacktoberfest-2023, please assign me this!

**Comment by Manishak798** [comment]
Go ahead with your work!
